name: Run ping test
on: [push]

jobs:
  run_test_net:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
        id: go
      - name: setup module
        run: |
          git submodule init
          git submodule sync
          git submodule update
      - name: prepare
        run: |
          sudo ./ubuntu-22-dev/scripts/setup_bpf.sh
          sudo make build
      - name: run test network
        run: |
          cd test
          sudo ./test_ping.sh